// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEditor;
using UnityEngine;
namespace TestProject
{
	public static class GUIPlaceholderMenu
	{
		[MenuItem("GameObject/Create Other/GUI Placeholder", false, 500)]
		static void CreateGUIPlaceholder()
		{
			GameObject obj = new GameObject();
			GUIContentHolder content = obj.AddComponent<GUIContentHolder>();
			GUIStylePrefab style = obj.AddComponent<GUIStylePrefab>();

			obj.name = "GUI Placeholder";

			content.text = "Placeholder";
			content.guiStylePrefab = style;

			style.lockScaleRatio = false;
			style.scale.x = 20;
			style.scale.y = 20;
			style.lockScaleRatio = true;

			Texture2D tex = AssetDatabase.LoadAssetAtPath("Assets/Animator/Files/Resources/am_box_red.png", typeof(Texture2D)) as Texture2D;
			style.normalBackground = tex;

			EditorUtility.DisplayDialog ("Information", "Switch to the Game tab to see the GUI in action.\nYour new placeholder is called 'GUI Placeholder'", "Ok");
		}

		[MenuItem("GameObject/Create Other/GUI Menu", false, 501)]
		static void CreateGUIMenu()
		{
			GameObject obj = new GameObject();
			GUIMenu menu = obj.AddComponent<GUIMenu>();
			
			obj.name = "GUI Menu";
			menu.visible = true;

			EditorUtility.DisplayDialog ("Information", "Your new menu is called 'GUI Menu'\nDrag GUI Placeholders or real GUI objects inside it to create a menu.", "Ok");
		}
	}
}

