// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections.Generic;

namespace TestProject
{
	[System.Serializable]
	public class GameEffect
	{
		public AudioClip playSoundEffect;
		public AudioClip loopSoundEffect;
		public GameObject spawnPrefab;
		public Mesh swapToMesh;
		public List<Material> swapToMaterials;
		public ParticleSystem emitParticle;
		public ParticleSystem loopParticle;
	}
}

